name: Keep HuggingFace Spaces Awake

on:
  schedule:
    - cron: "*/15 * * * *"   # runs every 30 minutes
  workflow_dispatch:

jobs:
  ping-spaces:
    runs-on: ubuntu-latest

    steps:
      - name: Ping HuggingFace Spaces
        run: |
          urls=(
            "https://kalpkanungo-multimodal-en-de-translator.hf.space"
            "https://kalpkanungo-geovistar.hf.space"
            "https://kalpkanungo-eventface.hf.space"
            "https://kalpkanungo-Reflex_rag.hf.space"
            "https://kalpkanungo-scenegraphnet.hf.space"
          )

          for url in "${urls[@]}"; do
            echo "Pinging $url"
            curl -L --max-time 30 -s -o /dev/null $url
          done
